### ISSUE TITLE
No hosts found when attempting to fetch SQL dump from WP Engine

### ISSUE THREAD

**Issue by milojennings** [INN/deploy-tools#16]
I've got the fabfile.py filled out, but when I run ```fab wp.fetch_sql_dump``` I get the message: ```No hosts found. Please specify (single) host string for connection:```

If I manually enter the hostname, it attempts to connect using my OSX username and doesn't provide the option of changing the user. 

Maybe I don't have my fabfile.py filled out correctly. This is what I've got so far:

	# Environments
	@task
	def production():
	    """
	    Work on production environment
	    """
	    env.settings    = 'production'
	    env.hosts       = ['example.wpengine.com']    # ssh host for production.
	    env.user        = 'example'    # ssh user for production.
	    env.password    = '********'    # ssh password for production.

Any help would be greatly appreciated. Thanks

**Comment by rnagle** [comment]
You must specify an environment by adding the `staging` or `production` task to your overall fab command. Try:

    fab staging wp.fetch_sql_dump

or

    fab production wp.fetch_sql_dump

Note: you should change `env.hosts` so that it contains the host of your SFTP server. Likewise, `env.user` and `env.password` should be the username and password of an account that has access to the SFTP server on the specified host.

**Comment by milojennings** [comment]
Awesome! That worked perfectly. Thanks for your help.

**Comment by rnagle** [comment]
Excellent! Any time.
