### ISSUE TITLE
Enhancement: bash/shell tab completion for commands

### ISSUE THREAD

**Issue by benlk** [INN/deploy-tools#19]
It would be nice to have tab completion for deploy tools commands.

It may be possible to automatically generate these with [optcomplete](http://furius.ca/optcomplete/), with [something specific to fabric](http://www.evans.io/posts/bash-tab-completion-fabric-ubuntu/), or we may have to compose them by hand.

This features [is planned for Fabric eventually](https://github.com/fabric/fabric/issues/6).

**Comment by rnagle** [comment]
I agree this would be nice to have.

I've tried one tab completion script for Fabric but ultimately gave up as it was excruciatingly slow.

**Comment by rnagle** [comment]
I'm going to close this since there are some bash snippets capable of doing this to varying degrees.

Also, as noted in the thread linked to in the original description, it seems like it might be harder problem than even the maintainers of fabric initially anticipated.

I think that places this problem solidly outside the scope of our modest deploy tools.

**Comment by benlk** [comment]
https://debian-administration.org/article/316/An_introduction_to_bash_completion_part_1
